<a href="https://colab.research.google.com/github/Lakshayakanna123/NLP-pdf-feature-extraction-and-retrieval/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.17.0


In [ ]:
#create a constant tensor A

A = tf.constant([[4,3],[6,1]]) #constant
print(A)

tf.Tensor(
[[4 3]
 [6 1]], shape=(2, 2), dtype=int32)


In [ ]:
#create a variable tensor V

V = tf.Variable([[1,2,3],[4,5,6]]) #Variable
print(V)
B = tf.constant([[5,8],[9,5]]) #constant
print(B)


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
tf.Tensor(
[[5 8]
 [9 5]], shape=(2, 2), dtype=int32)


In [ ]:
#concatenate

AB = tf.concat([A,B],0)
print(AB)

tf.Tensor(
[[4 3]
 [6 1]
 [5 8]
 [9 5]], shape=(4, 2), dtype=int32)


In [ ]:
tensor = tf.zeros([2,3])
print(tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
tensor = tf.ones([2,3])
print(tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
tensor = tf.eye(3)
print(tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
tensor = tf.random.normal([2,3])
print(tensor)

tf.Tensor(
[[ 0.43586022  0.39169848 -0.1171051 ]
 [ 0.16484323 -0.49192494 -1.0937563 ]], shape=(2, 3), dtype=float32)


In [ ]:
tensor = tf.random.uniform([2,3])
print(tensor)

tf.Tensor(
[[0.88031197 0.4105066  0.53318536]
 [0.18138313 0.5683539  0.8430693 ]], shape=(2, 3), dtype=float32)


In [ ]:
shape = tf.reshape(tensor,[3,2])

In [ ]:
#typecast

tensor=tf.constant([[1.8,2.3],
                   [4.2,5.5],
                   [5.2,9.0],
                   [7.1,2.5]],
                   dtype=tf.float32)
print(tensor)
casted_tensor = tf.cast(tensor,dtype=tf.int32)
print(casted_tensor)

tf.Tensor(
[[1.8 2.3]
 [4.2 5.5]
 [5.2 9. ]
 [7.1 2.5]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[1 2]
 [4 5]
 [5 9]
 [7 2]], shape=(4, 2), dtype=int32)


In [ ]:
print(tensor)

tf.Tensor(
[[1.8 2.3]
 [4.2 5.5]
 [5.2 9. ]
 [7.1 2.5]], shape=(4, 2), dtype=float32)


In [ ]:
a=tf.transpose(tensor)
print(a)

tf.Tensor(
[[1.8 4.2 5.2 7.1]
 [2.3 5.5 9.  2.5]], shape=(2, 4), dtype=float32)


In [ ]:
a= tf.constant([[1,2],[4,5]])

v = tf.constant([[5],
                [6]])

av = tf.matmul(a,v)
print(av)


tf.Tensor(
[[17]
 [50]], shape=(2, 1), dtype=int32)


In [ ]:
av = tf.multiply(a,v)
print(av)

tf.Tensor(
[[ 5 10]
 [24 30]], shape=(2, 2), dtype=int32)


In [ ]:
import datetime, warnings,scipy
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.style.use("fivethirtyeight")
mpl.rcParams["patch.force_edgecolor"] = True
warnings.filterwarnings("ignore")
%matplotlib inline
mpl.rc('patch',edgecolor='black',linewidth=1)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('display.max_columns',None)

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.5349721 , -0.1241605 , -0.36117768, -1.1782677 ,  0.00762047,
        -0.2618331 , -0.72433114, -0.8320066 , -0.46197322, -0.24487354]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.08896203, 0.13415842, 0.105848  , 0.04675467, 0.15305576,
        0.11690349, 0.07361514, 0.06610043, 0.09569906, 0.11890303]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.1464067

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8606 - loss: 0.4702
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9574 - loss: 0.1455
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9669 - loss: 0.1091
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9731 - loss: 0.0864
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9764 - loss: 0.0747


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9767 - loss: 0.0735


[0.07347840815782547, 0.9767000079154968]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.2868427e-09, 1.6785108e-09, 1.9374878e-05, 6.7890942e-05,
        5.2089161e-10, 4.5624763e-08, 4.2668218e-13, 9.9991000e-01,
        6.1290729e-07, 1.9546017e-06],
       [2.0164502e-10, 3.4562111e-04, 9.9965310e-01, 1.2789829e-06,
        3.3388395e-16, 5.2348700e-08, 2.8591153e-08, 4.4029433e-15,
        3.2531569e-09, 1.2628811e-13],
       [2.0418902e-08, 9.9977058e-01, 4.5227265e-05, 8.2277074e-07,
        3.6841616e-06, 1.2158512e-06, 1.2679945e-06, 1.4052256e-04,
        3.6334579e-05, 3.6730739e-07],
       [9.9932551e-01, 4.6444808e-07, 1.4163652e-05, 7.0695580e-07,
        3.5797352e-06, 9.7782993e-07, 6.1129936e-04, 4.0477524e-05,
        5.9748665e-08, 2.8523107e-06],
       [1.4572536e-05, 1.6075631e-08, 8.9325935e-05, 3.4945373e-08,
        9.9648488e-01, 6.3221535e-07, 2.0490039e-05, 8.2484272e-05,
        6.5728392e-07, 3.3068918e-03]], dtype=float32)>